### PR TITLE
Strip wrapping parens from around default gemset returned by rvm info

### PR DESCRIPTION
**Pull request by jjrussell**
fixes https://github.com/senny/rvm.el/issues/51

### CODE REVIEW

**Comment by senny** [comment]
@jjrussell thanks :yellow_heart:

Could you add a test-case to prevent against regressions?

**Comment by jjrussell** [comment]
mmmmmaybe? Not familiar with the test framework but I'll take a look.

**Comment by senny** [comment]
@jjrussell let me know if you have any questions.

**Comment by jjrussell** [comment]
OK, how's this?

**Comment by senny** [comment]
@jjrussell :yellow_heart: thanks man!

**Comment by senny** [comment]
I uploaded a new release 1.4.0.

**Comment by jjrussell** [comment]
WOohoo! Thanks.

I'll probably be using rbenv.el soon. Thanks for writing that too.

**Pull request merged**
